-- Demo data loaded once, when the database is first created.
-- Statements are split on a semicolon at the end of a line, so no literal below may contain one.
-- Users are inserted from DatabaseSeeder because their passwords must be hashed on the device.

INSERT INTO tags (_id, name) VALUES
    (1, 'advanced'),
    (2, 'algebra'),
    (3, 'basics'),
    (4, 'exam'),
    (5, 'formulas'),
    (6, 'humanities'),
    (7, 'science'),
    (8, 'space'),
    (9, 'trivia');

INSERT INTO questions (_id, name, answer) VALUES
    (1, 'Which planet is closest to the Sun?', 'Mercury'),
    (2, 'What galaxy contains our Solar System?', 'The Milky Way'),
    (3, 'What force keeps planets in orbit?', 'Gravity'),
    (4, 'Which organelle produces energy in a cell?', 'The mitochondrion'),
    (5, 'What molecule carries genetic information?', 'DNA'),
    (6, 'How many chambers does the human heart have?', 'Four'),
    (7, 'What is the chemical symbol for gold?', 'Au'),
    (8, 'What is the pH of pure water at 25 degrees Celsius?', '7'),
    (9, 'Which gas do plants absorb during photosynthesis?', 'Carbon dioxide'),
    (10, 'What is the capital of Portugal?', 'Lisbon'),
    (11, 'Which river flows through Egypt?', 'The Nile'),
    (12, 'Which is the largest ocean on Earth?', 'The Pacific Ocean'),
    (13, 'In which year did the Second World War end?', '1945'),
    (14, 'Who was the first President of the United States?', 'George Washington'),
    (15, 'Which empire built the Colosseum?', 'The Roman Empire'),
    (16, 'What is the derivative of x squared?', '2x'),
    (17, 'How do you solve a quadratic equation?', 'With the quadratic formula'),
    (18, 'What is the value of pi to two decimal places?', '3.14'),
    (19, 'What does SQL stand for?', 'Structured Query Language'),
    (20, 'Which SQLite wildcard matches a single character?', 'The underscore character'),
    (21, 'What is the difference between a class and an object?', 'A class is a blueprint and an object is an instance of it'),
    (22, 'Which Android component draws a scrolling list?', 'RecyclerView'),
    (23, 'How many players are on a football pitch per team?', 'Eleven'),
    (24, 'How often are the Summer Olympics held?', 'Every four years'),
    (25, 'Which language is spoken in Brazil?', 'Portuguese');

INSERT INTO question_tags (question_id, tag_id) VALUES
    (1, 3), (1, 8),
    (2, 8), (2, 9),
    (3, 4), (3, 7), (3, 8),
    (4, 4), (4, 7),
    (5, 3), (5, 7),
    (6, 3), (6, 9),
    (7, 3), (7, 7),
    (8, 4), (8, 5), (8, 7),
    (9, 7), (9, 9),
    (10, 3), (10, 9),
    (11, 3), (11, 9),
    (12, 4), (12, 9),
    (13, 4), (13, 6),
    (14, 6), (14, 9),
    (15, 6), (15, 9),
    (16, 1), (16, 2), (16, 5),
    (17, 2), (17, 4), (17, 5),
    (18, 3), (18, 5),
    (19, 1), (19, 4),
    (20, 1), (20, 3),
    (21, 1), (21, 4),
    (22, 1), (22, 9),
    (23, 3), (23, 9),
    (24, 9),
    (25, 6), (25, 9);

-- Further wordings of the same answer. Each is marked correct just as the answer above is, so a
-- learner who knows the fact is not failed by the form it was asked for.
INSERT INTO alternative_answers (_id, question_id, answer) VALUES
    (1, 2, 'Milky Way'),
    (2, 3, 'Gravitation'),
    (3, 4, 'Mitochondrion'),
    (4, 4, 'Mitochondria'),
    (5, 5, 'Deoxyribonucleic acid'),
    (6, 6, '4'),
    (7, 8, 'Seven'),
    (8, 9, 'CO2'),
    (9, 9, 'CO₂'),
    (10, 10, 'Lisboa'),
    (11, 11, 'Nile'),
    (12, 12, 'Pacific Ocean'),
    (13, 12, 'Pacific'),
    (14, 14, 'Washington'),
    (15, 15, 'Roman Empire'),
    (16, 15, 'Rome'),
    (17, 16, '2 x'),
    (18, 17, 'The quadratic formula'),
    (19, 17, 'Quadratic formula'),
    (20, 18, '3,14'),
    (21, 20, 'Underscore'),
    (22, 20, '_'),
    (23, 22, 'Recycler View'),
    (24, 23, '11'),
    (25, 24, 'Every 4 years'),
    (26, 24, 'Once every four years'),
    (27, 25, 'Brazilian Portuguese');
